trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
  
    # Install Docker Compose
  - script: sudo apt-get update && sudo apt-get install -y docker-compose
    displayName: 'Install Docker Compose'

  # Launch the PostgreSQL database using the docker-compose.yml file
  - script: docker-compose -f docker-compose.yml up -d
    displayName: 'Start PostgreSQL database in Docker'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: '**/*.csproj'
  
    # Install EF Tools
  - task: DotNetCoreCLI@2
    displayName: 'Install EF Tools'
    inputs:
      command: 'install'
      packagesToInstall: 'dotnet-ef'
      versioningScheme: 'latestMajor'

  # Update the database
  - script: |
      echo "##vso[task.prependpath]$HOME/.dotnet/tools"
      dotnet ef database update --project P4P/P4P.csproj
    displayName: 'Update Database'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration)'
      projects: '**/*Tests.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Publish'
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/WebApp'
      projects: 'P4P-Backend/*.csproj'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApp'
      artifactName: 'WebApp'