version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: P4P
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: